stages:     
  - passar-sonar  
  - buildar
  - implantar


checagem-sonar:
  stage: passar-sonar
  #tags: ["paraiso-runner-sh"]
  image: mcr.microsoft.com/dotnet/sdk:8.0
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
    GIT_DEPTH: "0"  
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
      - cd src/paraiso.web/
      - ls
      - dotnet sonarscanner begin /k:"paraiso-proibido_web-front_AZL5iGpgOlKdynBn1dsH" /d:sonar.host.url=$SONAR_HOST_URL  /d:sonar.token=$SONAR_TOKEN
      - dotnet build paraiso.web.csproj
      - dotnet sonarscanner end /d:sonar.token=$SONAR_TOKEN

  allow_failure: true
  only:
    - merge_requests
    - dev

buildar:
  stage: buildar
  tags: ["paraiso-runner-sh"]
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
      - rm -R /root/apps/dev/build/
      - cd src/paraiso.web/
      - dotnet build paraiso.web.csproj
      - dotnet publish -o /root/apps/dev/build/
  allow_failure: true
  only:
    - merge_requests
    - dev

Implantar:
  stage: implantar
  tags: ["paraiso-runner-sh"]
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
      - systemctl stop paraisoweb1.service
      - cp -rf /root/apps/dev/build/* /root/apps/dev/paraisoweb1/
      - systemctl start paraisoweb1.service
  allow_failure: true
  only:
    - merge_requests
    - dev